### ISSUE TITLE
Crash when hitting cancel

### ISSUE THREAD

**Issue by AaronRecord** [0xC0000054/pdn-content-aware-fill#4]
I hit cancel and paint.net crashed with this error:
```
File: C:\Program Files\paint.net\Effects\ContentAwareFill.dll
      Name: ContentAwareFill.ContentAwareFillEffect
      Version: 1.4.3.0
      Author: null54
      Copyright: Copyright © 2020 Nicholas Hayes (aka null54)
      Website: https://forums.getpaint.net/index.php?showtopic=112730
      Full error message: PaintDotNet.WorkerThreadException: Worker thread threw an exception ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'ContentAwareFillConfigDialog'.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at ContentAwareFill.Resynthesizer.Synthesize(Int32 pass, Func`1 abortCallback)
   at ContentAwareFill.Resynthesizer.ContentAwareFill(Func`1 abortCallback)
   at ContentAwareFill.ContentAwareFillEffect.OnSetRenderInfo(EffectConfigToken parameters, RenderArgs dstArgs, RenderArgs srcArgs)
   at PaintDotNet.Effects.BackgroundEffectRenderer.ThreadFunction() in D:\src\pdn\src\PaintDotNet\Effects\BackgroundEffectRenderer.cs:line 268
   --- End of inner exception stack trace ---
   at PaintDotNet.Effects.BackgroundEffectRenderer.DrainExceptions() in D:\src\pdn\src\PaintDotNet\Effects\BackgroundEffectRenderer.cs:line 447
   at PaintDotNet.Effects.BackgroundEffectRenderer.Abort() in D:\src\pdn\src\PaintDotNet\Effects\BackgroundEffectRenderer.cs:line 404
   at PaintDotNet.Effects.BackgroundEffectRenderer.Start() in D:\src\pdn\src\PaintDotNet\Effects\BackgroundEffectRenderer.cs:line 352
   at PaintDotNet.Menus.EffectMenuBase.<>c__DisplayClass43_3.<RunEffectImpl>b__4() in D:\src\pdn\src\PaintDotNet\Menus\EffectMenuBase.cs:line 904
```

**Comment by 0xC0000054** [comment]
Fixed in version 1.4.4.
